LOAD DATA LOCAL INFILE 'C:/Users/alonb/Desktop/FoxTrotOnline/lifemark/db/ClientsLifeMark1_20180827T231852.CSV'
INTO TABLE lifemark_jjixgbv9my802728.clients
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES;